spring.application.name=backend

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/aprovaai
spring.datasource.username=postgres
spring.datasource.password=6646

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Servidor
server.port=8080

# JWT
jwt.secret=MinhaChaveSuperSecretaAprovaAI2026BackendJWTMuitoSegura123456789
jwt.expiration=86400000